services:
  - type: web
    name: thynkly
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT main:app
    envVars:
      - key: SESSION_SECRET
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: thynkly-db
          property: connectionString
  - type: pserv
    name: thynkly-db
    env: postgresql
    plan: starter